spring:
  profiles:
    active: "dev"
  main:
    banner-mode: "off"

---
spring:
  profiles: dev
logging:
  level:
    org:
      springframework:
        security: DEBUG
    hibernate: DEBUG

  file: mylogfile.log

---
spring:
  profiles: prod
datasource:
  url: jdbc:mysql://localhost:3306/concretepage
  username: person
  password: cGVyc29uMzIx
  driver-class-name: com.mysql.jdbc.Driver
